name: qr_menu_system
description: "Menu system web app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: 14.6.3

  #Firebase
  firebase_core: 3.13.1
  cloud_firestore: 5.6.4
  firebase_storage: 12.4.6

  # State Management
  provider: ^6.1.2

  # Annotations
  json_annotation: 4.9.0
  freezed_annotation: 3.0.0

  logging: ^1.2.0
  
  # Environment
  flutter_dotenv: ^5.2.1

  # Shared
  shared:
    path: ./shared



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: 2.4.15
  freezed: 3.0.6
  json_serializable: ^6.9.5
  go_router_builder: 2.7.3


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/app_logo.png
    - assets/categories/
    - assets/products/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
dependency_overrides:
  freezed_annotation: 3.0.0