// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv2_yMCmpdVVhcAzr4cozC0fXMy1UMnes',
    appId: '1:693330187909:web:8cb9ed96be32ddb5837bec',
    messagingSenderId: '693330187909',
    projectId: 'qr-menu-system-7eb8e',
    authDomain: 'qr-menu-system-7eb8e.firebaseapp.com',
    storageBucket: 'qr-menu-system-7eb8e.firebasestorage.app',
    measurementId: 'G-XCG01S6MGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLg_dsusxNHXDmeslw2jzVkF5_Lq7u1kI',
    appId: '1:693330187909:android:f90ae1adeefad1f5837bec',
    messagingSenderId: '693330187909',
    projectId: 'qr-menu-system-7eb8e',
    storageBucket: 'qr-menu-system-7eb8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJ1U5HGaLb9-Np3KdkaLoze_jMDnb1Ps',
    appId: '1:693330187909:ios:4dcd29590fd483ed837bec',
    messagingSenderId: '693330187909',
    projectId: 'qr-menu-system-7eb8e',
    storageBucket: 'qr-menu-system-7eb8e.firebasestorage.app',
    iosBundleId: 'com.example.qrWebMenuAlshamiAlasl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJ1U5HGaLb9-Np3KdkaLoze_jMDnb1Ps',
    appId: '1:693330187909:ios:4dcd29590fd483ed837bec',
    messagingSenderId: '693330187909',
    projectId: 'qr-menu-system-7eb8e',
    storageBucket: 'qr-menu-system-7eb8e.firebasestorage.app',
    iosBundleId: 'com.example.qrWebMenuAlshamiAlasl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv2_yMCmpdVVhcAzr4cozC0fXMy1UMnes',
    appId: '1:693330187909:web:9e295e87b83d9d04837bec',
    messagingSenderId: '693330187909',
    projectId: 'qr-menu-system-7eb8e',
    authDomain: 'qr-menu-system-7eb8e.firebaseapp.com',
    storageBucket: 'qr-menu-system-7eb8e.firebasestorage.app',
    measurementId: 'G-JFPLCWDXJ7',
  );
}
